const domains_medical = "/image/domains/medical";
const domains_public = "/image/domains/public";
const domains_home = "/image/domains/home";
const domains_cannabis = "/image/domains/cannabis";
const domains_cold = "/image/domains/cold";
const products = "/image/litvaLampsImages";
const studies = "/image/studies";
const project = "/icons/recentProjects";
const home = "/image/fields";
const icons = "/icons";
const workWithUs = "/icons/workWithUsIcons/";
const productPage = "/image/products";

export const images = {
    domains_medical_bg: `${domains_medical}/medicalBg.png`,
    domains_medical_desc: `${domains_medical}/medical.png`,
    domains_public_bg: `${domains_public}/publicBg.png`,
    domains_public_desc: `${domains_public}/public.png`,
    domains_home_bg: `${domains_home}/homeBg.png`,
    domains_home_desc: `${domains_home}/home.png`,
    domains_cannabis_bg: `${domains_cannabis}/cannabisBg.png`,
    domains_cannabis_desc: `${domains_cannabis}/cannabis.png`,
    domains_cold_bg: `${domains_cold}/coldBg.png`,
    domains_cold_desc: `${domains_cold}/cold.png`,
    product1_big: `${products}/bigImg.png`,
    product1_small1: `${products}/smallImg.png`,
    product1_small2: `${products}/smallImg2.png`,
    product2_big2: `${products}/bigImg2.png`,
    product2_small1: `${products}/smallImg3.png`,
    product2_small2: `${products}/smallImg4.png`,
    product3_big3: `${products}/bigImg3.png`,
    product4_big4: `${products}/bigImg4.png`,
    product4_small1: `${products}/smallImg5.png`,
    product4_small2: `${products}/smallImg6.png`,
    product5_big5: `${products}/bigImg5.png`,
    product5_small1: `${products}/smallImg7.png`,
    product5_small2: `${products}/smallImg8.png`,
    product5_small3: `${products}/smallImg9.png`,
    product6_big6: `${products}/bigImg6.png`,
    product6_small1: `${products}/smallImg10.png`,
    product6_small2: `${products}/smallImg11.png`,
    studies1: `${studies}/sick.png`,
    studies2: `${studies}/test.png`,
    studies3: `${studies}/information.png`,
    studies4: `${studies}/breathe.png`,
    studies5: `${studies}/kill.png`,
    studies6: `${studies}/batteries.png`,
    studies7: `${studies}/cleaning.png`,
    studies8: `${studies}/cannabis.png`,
    project1: `${project}/enzymotech.svg`,
    project2: `${project}/superPharm.svg`,
    project3: `${project}/rambam.svg`,
    project4: `${project}/assuta.svg`,
    project5: `${project}/beit.svg`,
    project6: `${project}/holmes.svg`,
    project7: `${project}/cold.svg`,
    project8: `${project}/airoportAuthority.svg`,
    project9: `${project}/ichilov.svg`,
    project10: `${project}/garbage.svg`,
    project11: `${project}/ben.svg`,
    project12: `${project}/weizmann.svg`,
    project13: `${project}/shoam.svg`,
    project14: `${project}/soroka.svg`,
    project15: `${project}/blinson.svg`,
    project16: `${project}/schneider.svg`,
    project17: `${project}/clp.svg`,
    project18: `${project}/golan.svg`,
    homeFields1: `${home}/medicalInstitutions.png`,
    homeFields2: `${home}/medicalCanabisGrowers.png`,
    homeFields3: `${home}/foodIndustry.png`,
    homeFields4: `${home}/publicandCommercialBuildings.png`,
    homeFields5: `${home}/homeSolutions.png`,
    air_cleaner: `${icons}/airCleaner.svg`,
    our_products1: `${icons}/ourproducts-1.svg`,
    our_products2: `${icons}/ourproducts-2.svg`,
    our_products3: `${icons}/ourproducts-3.svg`,
    our_products4: `${icons}/ourproducts-4.svg`,
    work_with_us1: `${workWithUs}installation.png`,
    work_with_us2: `${workWithUs}definingNeeds.png`,
    work_with_us3: `${workWithUs}periodicChecks.png`,
    work_with_us4: `${workWithUs}match.png`,
    product1: `${productPage}/litva.png`,
    product2: `${productPage}/air.png`,
    product3: `${productPage}/s300fx.png`,
    product4: `${productPage}/disinfection.png`,
    product5: `${productPage}/system.png`,
    product6: `${productPage}/p900gx.png`,
    arrowRight: `rightArrow.svg`,
    arrowBottom: `bottomArrow.svg`,
    logoHeader: `${icons}/sagol-logo.svg`,
    facebook: `${icons}/facebook.svg`,
    linkedin: `${icons}/linkedin.svg`,
    instagram: `${icons}/instagram.svg`,
    twitter: `${icons}/twitter.svg`,
};
