export const navBarPaths = {
    about: "/about",
    products: "/products",
    litvalamps: "/products/litvalamps",
    air: "/products/air",
    deodorization: "/products/deodorization",
    disinfection: "/products/disinfection",
    system: "/products/system",
    p900gx: "/products/p900gx",
    medical: "/domains/medical",
    public: "/domains/public",
    home: "/domains/home",
    cannabis: "/domains/cannabis",
    cold: "/domains/cold",
    infoCenter: "/infoCenter",
    studies: "/studies",
    projects: "/projects",
    lectures: "/lectures",
    contactUs: "/contactUs",
    login: "/login",
    signUp: "/signup",
};
